Repository michaeleggers/Bayernstein, pull requests merged in 2024-10, with the labels that each got.

#12 fix: Windows build
  CMakeLists.txt
  game.cpp
  polysoup.cpp
Labels: enhancement

#10 feat: add github actions to build
  .github/workflows/build.yaml
Labels: CI/CD

#16 feat: 2d screenspace rendering
  CMakeLists.txt
  README.md
  assets/fonts/HackNerdFont-Bold.ttf
  assets/shaders/composite.frag
  assets/shaders/composite.vert
  assets/shaders/font.frag
  assets/shaders/font.vert
  assets/shaders/shapes2d.frag
  assets/shaders/shapes2d.vert
  dependencies/stb_truetype.h
  game.cpp
  game.h
  irender.h
  r_common.cpp
  r_common.h
  r_font.cpp
  r_font.h
  r_gl.cpp
  r_gl.h
  r_gl_batch.cpp
  r_gl_batch.h
  r_gl_fbo.cpp
  r_gl_fbo.h
  r_gl_rendertexture.cpp
  r_gl_rendertexture.h
  r_gl_shader.cpp
  r_gl_shader.h
  r_gl_texture.cpp
  r_gl_texture.h
  r_gl_texture_mgr.cpp
  r_gl_texture_mgr.h
  r_itexture.h
  r_model.cpp
  r_texture_mgr.cpp
Labels: Rendering

#14 feat: base game entity, state machines and messaging system
  .clang-format.bak
  .clang-tidy.bak
  .gitignore
  CMakeLists.txt
  CWorld.h
  Clock/clock.cpp
  Clock/clock.h
  Entity/Door/g_door.cpp
  Entity/Door/g_door.h
  Entity/Door/g_door_states.cpp
  Entity/Door/g_door_states.h
  Entity/Enemy/g_enemy.cpp
  Entity/Enemy/g_enemy.h
  Entity/Enemy/g_enemy_states.cpp
  Entity/Enemy/g_enemy_states.h
  Entity/Player/g_player.cpp
  Entity/Player/g_player.h
  Entity/Player/g_player_states.cpp
  Entity/Player/g_player_states.h
  Entity/base_game_entity.cpp
  Entity/base_game_entity.h
  Entity/entity_manager.cpp
  Entity/entity_manager.h
  FSM/istate.h
  FSM/state_machine.h
  Message/message_dispatcher.cpp
  Message/message_dispatcher.h
  Message/message_type.h
  Message/telegram.h
  assets/maps/minimal.map
  collision.cpp
  collision.h
  game.cpp
  game.h
  main.cpp
  map_parser.h
  polysoup.cpp
  polysoup.h
  r_common.h
  utils.h
Labels: AI, Engine, Entity System

#22 feat: combine player entity with model
  .clang-format
  .clang-tidy
  .gitignore
  Entity/Player/g_player.cpp
  Entity/Player/g_player.h
  game.cpp
  game.h
  r_model.h
  utils.cpp
  utils.h
Labels: Engine, Entity System
